xpra: 4.0.6 -> 4.1.1
pandoc is required during build, to render docs:

```
chmod(build/bdist.linux-x86_64/wheel/xpra-4.1.1.data/data/etc/dbus-1/system.d/xpra.conf, 0o644)
./docs               -> build/bdist.linux-x86_64/wheel/xpra-4.1.1.data/data/share/doc/xpra
./docs/Build         -> build/bdist.linux-x86_64/wheel/xpra-4.1.1.data/data/share/doc/xpra/Build
  MSWindows.md         -> MSWindows.html
error: [Errno 2] No such file or directory: 'pandoc'
builder for '/nix/store/880msh063y7ffh12nwnz4ryhlhlbbi9r-xpra-4.1.1.drv' failed with exit code 1
```