flutter: set dart versionUsed, not version
Seems to cause the following eval error otherwise:

```
error:
       … while calling the 'head' builtin

         at /nix/store/ngy0l9sly1qqg049584bwbiz9bb5x1mv-nixpkgs-src/lib/attrsets.nix:967:11:

          966|         || pred here (elemAt values 1) (head values) then
          967|           head values
             |           ^
          968|         else

       … while evaluating the attribute 'value'

         at /nix/store/ngy0l9sly1qqg049584bwbiz9bb5x1mv-nixpkgs-src/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'versionUsed' missing

       at /nix/store/ngy0l9sly1qqg049584bwbiz9bb5x1mv-nixpkgs-src/pkgs/development/compilers/dart/default.nix:8:13:

            7| , sources ? import ./sources.nix {inherit fetchurl;}
            8| , version ? sources.versionUsed
             |             ^
            9| }:
```